### ISSUE TITLE
请问我在运行train.py是报以下错误，是什么原因，麻烦解答一下，谢谢

### ISSUE THREAD

**Issue by Miger0629** [ikkyu-wen/huawei-garbage#10]
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 99, in main
    train_loss, train_acc, train_5 = train(train_loader, model, criterion, optimizer, epoch, use_cuda)
  File "train.py", line 158, in train
    inputs, targets = torch.atrutograd.Variable(inputs), torch.autograd.Variable(targets)
AttributeError: module 'torch' has no attribute 'atrutograd'

**Comment by Miger0629** [comment]
额，你代码train.py中的158行那里有错误autograd写成了atrutograd

**Comment by Miger0629** [comment]
不好意思，我 之前可能按到哪了，导致那个函数拼错了
